# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-pds-data-retention:
    build:
      target: development
    image: fcp-pds-data-retention-development
    container_name: fcp-pds-data-retention-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - fcp-pds-data-retention
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING};BlobEndpoint=http://ffc-pay-batch-azurite:10000/devstoreaccount1;
    depends_on:
      - fcp-pds-data-retention-azurite

  fcp-pds-data-retention-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10008:10000"

  fcp-pds-data-retention-postgres:
    ports:
      - "5490:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  fcp-pds-data-retention:
    name: fcp-pds-data-retention
    driver: bridge

volumes:
  azurite_data:
  postgres_data: