# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-pds-data-retention:
    build:
      target: development
    image: fcp-pds-data-retention-development
    ports:
      - "9245:9229"
    container_name: fcp-pds-data-retention-development
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    depends_on:
      - fcp-pds-data-retention-azurite

  fcp-pds-data-retention-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10008:10000"

  fcp-pds-data-retention-postgres:
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  azurite_data:
  postgres_data: