# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  fcp-pds-data-retention:
    build:
      target: development
    image: fcp-pds-data-retention-development
    container_name: fcp-pds-data-retention-test
    depends_on:
      - fcp-pds-data-retention-postgres
      - fcp-pds-data-retention-azurite
      - servicebus-emulator
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
      PROCESSING_ACTIVE: true
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-batch-azurite:10000/devstoreaccount1;
      MESSAGE_QUEUE_HOST: servicebus-emulator
      MESSAGE_QUEUE_USER: RootManageSharedAccessKey
      MESSAGE_QUEUE_PASSWORD: SAS_KEY_VALUE
      EVENTS_TOPIC_ADDRESS: ffc-pay-events-test
      NODE_ENV: test

  fcp-pds-data-retention-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fcp-pds-data-retention-azurite:
    labels:
      com.docker.compose.pds.role: test

  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DummyStrongPa$$w0rd" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16

  servicebus-emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "./BusConfig.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "DummyStrongPa$$w0rd" # Password should be same as what is set for SQL Edge
      ACCEPT_EULA: "Y"
    depends_on:
      - sqledge

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5672"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  postgres_data: {}
