# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-pds-data-retention:
    build:
      target: development
    image: fcp-pds-data-retention-development
    container_name: fcp-pds-data-retention-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - fcp-pds-data-retention

networks:
  fcp-pds-data-retention:
    name: fcp-pds-data-retention
    driver: bridge
