services:
  fcp-pds-data-retention:
    build:
      context: .
      target: production
    image: fcp-pds-data-retention
    container_name: fcp-pds-data-retention
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-pds-data-retention-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
