#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^fcp-pds$ --format={{.Name}})" ]; then
  echo "Creating fcp-pds Docker network"
  docker network create fcp-pds
fi

if [ -n "$(docker container ls --filter label=com.docker.compose.pds.role=fcp-pds-data-retention-azurite --format={{.ID}})" ]; then
  echo "Azurite container already exists, skipping creation"
  args="--scale fcp-pds-data-retention-azurite=0"
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker compose down
docker compose -f docker-compose.migrate.yaml down
# Ensure container images are up to date
docker compose -f docker-compose.migrate.yaml run --rm database-up

docker compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $args $@
